captcha:
    length: 4
    open: false
casbin:
    autoloadpolicyseconds: 120
    modelconfig: |
        [request_definition]
        r = sub, obj, act
        [policy_definition]
        p = sub, obj, act
        [role_definition]
        g = _, _
        [policy_effect]
        e = some(where (p.eft == allow))
        [matchers]
        m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && r.act == p.act
    tablename: casbin_rule
    tableprefix: ""
gormv2:
    mysql:
        isinitglobalgormmysql: 1
        isopenreaddb: 0
        read:
            charset: utf8mb4
            database: gin-fast
            host: 127.0.0.1
            pass: root
            port: 3306
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: root
        slowthreshold: 30
        write:
            charset: utf8mb4
            database: gin-fast
            host: 127.0.0.1
            pass: root
            port: 3306
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: root
    postgresql:
        isinitglobalgormpostgresql: 0
        isopenreaddb: 0
        read:
            database: gin-fast
            host: 127.0.0.1
            pass: ""
            port: 5432
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: ""
        slowthreshold: 30
        write:
            database: gin-fast
            host: 127.0.0.1
            pass: ""
            port: 5432
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: ""
    sqlserver:
        isinitglobalgormsqlserver: 0
        isopenreaddb: 0
        read:
            database: gin-fast
            host: 127.0.0.1
            pass: ""
            port: 1433
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: ""
        slowthreshold: 30
        write:
            database: gin-fast
            host: 127.0.0.1
            pass: ""
            port: 1433
            prefix: ""
            setconnmaxidletime: 30
            setconnmaxlifetime: 60
            setmaxidleconns: 10
            setmaxopenconns: 128
            user: ""
    usedbtype: mysql
httpserver:
    allowcrossdomain: true
    port: :8080
    serverroot: ./resource/public
    serverrootpath: /public
logs:
    compress: false
    ginlogname: /resource/logs/gin.log
    maxage: 15
    maxbackups: 7
    maxsize: 10
    textformat: console
    timeprecision: second
    zaplogname: /resource/logs/ginfast.log
redis:
    connfailretrytimes: 3
    host: 127.0.0.1
    idletimeout: 60
    indexdb: 1
    maxactive: 1000
    maxidle: 10
    password: ""
    port: 6379
    reconnectinterval: 1
safe:
    loginlockduration: 10
    loginlockexpire: 10
    loginlockthreshold: 2
    minpasswordlength: 6
    requirespecialchar: true
server:
    appdebug: true
    cachetype: memory
system:
    systemcopyright: Copyright © 2022 - present gin-fast 版权所有
    systemicon: /public/uploads/2025-10-10/20251010_95508faf-7cdf-4f6c-9dbc-b4c58d66379b.ico
    systemlogo: /public/uploads/2025-10-10/20251010_d5b3fe78-bf41-43fb-ab36-548fc3cfaad1.svg
    systemname: GinFast
    systemrecordno: 粤ICP备12345678号
token:
    cachekeyprefix: 'gin-fast:'
    jwttokenexpire: 3600
    jwttokenrefreshexpire: 2592000
    jwttokensignkey: gin-fast
upload:
    allowed_types:
        - .jpg
        - .jpeg
        - .png
        - .gif
        - .bmp
        - .pdf
        - .doc
        - .docx
        - .xls
        - .xlsx
        - .txt
        - .zip
        - .rar
        - .svg
        - .ico
    local_path: ./resource/public/uploads
    max_size: 10
    qiniu_config:
        access_key: ""
        bucket: ""
        domain: ""
        secret_key: ""
        zone: ZoneHuadong
    upload_type: local
