Server:
  AppDebug: true   # 设置程序所处的模式，debug=true 调试模式，日志优先显示在控制台， debug=false 非调试模式，日志将写入日志文件
  CacheType: "redis" #缓存模式 memory OR redis
HttpServer:
  Port: ":8080"
  AllowCrossDomain: true    #是否允许跨域
Token:
  JwtTokenSignKey:  "gin-fast"   #设置token生成时加密的签名
  JwtTokenExpire:  43200    #设置token过期时间，单位秒 默认43200=12小时
  JwtTokenRefreshExpire:  2592000  #设置刷新token过期时间，单位秒 默认2592000=30天
  CacheKeyPrefix: "gin-fast:"  # 缓存前缀
Redis:
  Host: "127.0.0.1"
  Port: 6379
  Password: ""  # 设置你的redis密码
  MaxIdle: 10
  MaxActive: 1000
  IdleTimeout: 60
  IndexDb: 1               # 默认连接的redis是1号数据库，不是0号数据库
  ConnFailRetryTimes: 3    #从连接池获取连接失败，最大重试次数
  ReConnectInterval: 1     # 从连接池获取连接失败，每次重试之间间隔的秒数
Logs:
  GinLogName: "/resource/logs/gin.log"                  #设置 gin 框架的接口访问日志，v1.5.xx 以后的版本不再生成gin原生的接口访问日志
  ZapLogName: "/resource/logs/ginfast.log"    #设置项目骨架运行时日志文件名，注意该名称不要与上一条重复 ,避免和 gin 框架的日志掺杂一起，造成混乱。
  TextFormat: "console"                                   #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
  TimePrecision: "second"                   #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 10                                             #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 7                                        #保留旧日志最大个数
  MaxAge: 15                                            #保留旧日志最大天数
  Compress: false                                      #日志备份时，是否进行压缩
Casbin:
  AutoLoadPolicySeconds: 30 # 扫描数据库策略的频率(单位：秒)
  TablePrefix: ""
  TableName: "casbin_rule" 
  ModelConfig: | # 竖线 | 表示以下整段文本保持换行格式
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && r.act == p.act
Captcha:
  length: 4   # 验证码生成时的长度
Gormv2: # 只针对 gorm  操作数据库有效
  UseDbType: "mysql"   # 默认使用的数据库类型（mysql、sqlserver、postgresql）
  Mysql:
    IsInitGlobalGormMysql: 1      # 随项目启动初始化一个全局变量 gorm.Db（1=开启、0=关闭）
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Write:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 3306
      Prefix: ""
      User: "root"
      Pass: "root" 
      Charset: "utf8mb4"
      SetMaxIdleConns: 10    # 最大空闲连接数
      SetMaxOpenConns: 128   # 最大打开连接数
      SetConnMaxLifetime: 60    # 连接最大生存时间(秒)
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
    IsOpenReadDb: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 3306                        #注意，非3306，请自行调整
      Prefix: ""
      User: "root"
      Pass: "root"  # 修改为你自己的数据库密码
      Charset: "utf8mb4"
      SetMaxIdleConns: 10    # 最大空闲连接数
      SetMaxOpenConns: 128    # 最大打开连接数
      SetConnMaxLifetime: 60    # 连接最大生存时间(秒)
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
  SqlServer:
    IsInitGlobalGormSqlserver: 0  # 随项目启动初始一个全局变量 gorm.Db（1=开启、0=关闭）
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 1433
      Prefix: ""
      User: ""
      Pass: ""
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭
    Read:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 1433
      Prefix: ""
      User: ""
      Pass: ""
      SetMaxIdleConns: 10   
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60  # 连接最大生存时间(秒)
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
  PostgreSql:
    IsInitGlobalGormPostgreSql: 0   # 随项目启动初始一个全局变量 gorm.Db（1=开启、0=关闭）
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 5432
      Prefix: ""
      User: ""
      Pass: ""
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "gin-fast"
      Port: 5432
      Prefix: ""
      User: ""
      Pass: ""
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      SetConnMaxIdleTime: 30    # 空闲连接最大存活时间(秒)
